project_name: open-ai-rag
aws_region: us-west-1
default_bucket: mlopswithsagemaker111
sagemaker_execution_role_arn: arn:aws:iam::659613508664:role/service-role/AmazonSageMaker-ExecutionRole-20230507T235254

pipeline:
  name: open-ai-rag-sagemaker-pipeline
  base_job_prefix: open-ai-rag

model:
  model_package_group_name: open-ai-rag-package-group
  approval_status: PendingManualApproval
  inference_instance_type: ml.m5.large
  training_instance_type: ml.m5.large
  target_column: sales
  feature_columns:
    - age
    - gender
    - miles
    - debt
    - income

data:
  local_path: data/raw/cars_1020.csv
  s3_prefix: open-ai-rag/input

endpoints:
  staging:
    name: open-ai-rag-staging
    instance_type: ml.m5.large
    initial_instance_count: 1
  production:
    name: open-ai-rag-prod
    instance_type: ml.m5.large
    initial_instance_count: 1

openai:
  model: gpt-5.2
  max_output_tokens: 700

rag:
  knowledge_base_path: data/rag/car_sales_knowledge.txt
  top_k: 3
